CREATE TABLE public.cities (
       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       "name" text NOT NULL,
       CONSTRAINT cities_pk PRIMARY KEY (id)
);

CREATE TABLE public.users (
      id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "name" text NOT NULL,
      city_id int8 NOT NULL,
      CONSTRAINT users_pk PRIMARY KEY (id),
      CONSTRAINT city_fk FOREIGN KEY (city_id) REFERENCES public.cities(id)
);

CREATE TABLE public.roles (
      id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "name" text NOT NULL,
      CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE public.users_roles (
        user_id int8 NOT NULL,
        role_id int8 NOT NULL,
        CONSTRAINT users_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
        CONSTRAINT roles_fk FOREIGN KEY (role_id) REFERENCES public.roles(id)
);